logFilters:
  - code: YN0060
    level: discard
  - code: YN0002
    level: discard

nodeLinker: node-modules

enableScripts: false

nmMode: hardlinks-local

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs

# Based on open issue: Storybook 7 migration not sucessful in monorepo
# https://github.com/storybookjs/storybook/issues/21710#issuecomment-1504976732
packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "7.0.12"
